version: "3"

services:
  cihm-cantaloupe:
    build: .
    environment:
      - REPOSITORY_BASE
    image: cihm-cantaloupe:latest
    ports:
      - "8182:8182"
    volumes:
      - /repository:/repository
